### ISSUE TITLE
White background underneath the navigation bar

### ISSUE THREAD

**Issue by hazem-saeed** [immi420/crystal_navigation_bar#2]
When I tried to use your package, a white background is beneath the navigation bar, although in the pics the background is transparent.

Here's my code:

```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      extendBody: true,
      body: _pageChooser(pageIndex),
      bottomNavigationBar: CrystalNavigationBar(
        currentIndex: pageIndex,
        height: 10,
        indicatorColor: Theme.of(context).colorScheme.secondary,
        unselectedItemColor: disabledColor,
        backgroundColor: Theme.of(context).colorScheme.primary,
        onTap: (index) => setState(() => pageIndex = index),
        items: crystalNavigationBarIcons.map((item) =>
          CrystalNavigationBarItem(
            icon: item,
            selectedColor: Theme.of(context).colorScheme.secondary
          )
        ).toList()
      )
    );
  }
```

And one more question, is there a feature to hide the navigation bar when scrolling?

**Comment by immi420** [comment]
Hey @hazem-saeed 
Unfortunately, I can't reproduce this issue using your code.
can you provide your flutter version, material 3 support enabled, and more details?

<img width="426" alt="Screen Shot 2024-01-10 at 1 40 23 AM" src="https://github.com/immi420/crystal_navigation_bar/assets/30823817/f0bf0061-4621-4321-96f1-2f6d17a10196">

**Comment by immi420** [comment]
Hide the navigation bar when scrolling is in my TODO for future updates.

**Comment by olerhan** [comment]
This issue also happens to me. It was actually the main reason I tried your package. It looks like the blur bleeds and isn’t clipped—ClipRect doesn’t seem to fully constrain the blur, which results in a visible light/white strip under the floating bar.
Environment
	•	Flutter: 3.32.5
	•	iOS: 17.5 (reproducible on both physical device and simulator)
	•	Material 3: enabled (ThemeData(useMaterial3: true))
Observed Behavior
	•	A thin white/bright “strip” shows up under the floating bar.
	•	The blur appears to extend outside its clipped bounds (i.e., ClipRect doesn’t seem to clip the blur pass fully).

Expected Behavior
	•	The bar should appear cleanly “floating” with no bright/white strip beneath it.
	•	Blur should be fully clipped to the bar’s rounded rect.

`class MainPage extends StatelessWidget {
  const MainPage({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context); // useMaterial3: true

    return Scaffold(
      extendBody: true,
      extendBodyBehindAppBar: true,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        // flexibleSpace uses a blurred backdrop (works fine for app bar)
        flexibleSpace: ClipRect(
          child: BackdropFilter(
            filter: ImageFilter.blur(sigmaX: 7.5, sigmaY: 7.5),
            child: Container(
              color: theme.colorScheme.primary.withValues(alpha: 0.5),
            ),
          ),
        ),
      ),
      backgroundColor: theme.colorScheme.surface,
      body: /* IndexedStack or other page content — redacted */,
      bottomNavigationBar: SafeArea(
        minimum: const EdgeInsets.only(bottom: 12),
        child: CrystalNavigationBar(
          height: 72,
          enableFloatingNavBar: true,
          margin: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
          borderRadius: 24,
          splashBorderRadius: 24,

          // translucent background & indicator (example values)
          backgroundColor: theme.colorScheme.surfaceContainer.withValues(alpha: 0.50),
          indicatorColor: theme.colorScheme.secondaryContainer.withValues(alpha: 0.60),

          selectedItemColor: theme.colorScheme.primary,
          unselectedItemColor: theme.colorScheme.onSurfaceVariant,
          outlineBorderColor: Colors.transparent,
          borderWidth: 0.0,

          currentIndex: /* redacted */,
          onTap: /* redacted */,
          items: [
            // icons redacted
            const CrystalNavigationBarItem(icon: Icons.home),
            const CrystalNavigationBarItem(icon: Icons.search),
            const CrystalNavigationBarItem(icon: Icons.person),
          ],
        ),
      ),
    );
  }
}`

<img width="1242" height="1017" alt="Image" src="https://github.com/user-attachments/assets/998d44fc-2664-4146-8d62-c590fc4e1950" />
