### ISSUE TITLE
selectedIcon always set to home.

### ISSUE THREAD

**Issue by hacker0id** [immi420/crystal_navigation_bar#3]
In my code I refactored crystal_nav_bar to be able to use it app-wide (on all screens),
when I click say profiles page and I have added navigator if _selectedTab == _SelectedTab.profile, it no doubt navigates me to the ProfilePage(), however it doesn't change the active icon to profile...

Attaching Screenshots :

![Simulator Screenshot - iPhone 15 Pro - 2024-01-07 at 05 24 13](https://github.com/immi420/crystal_navigation_bar/assets/50419120/e336a9f8-ac2c-4d5f-b717-39741f70b7c2)
![Simulator Screenshot - iPhone 15 Pro - 2024-01-07 at 05 24 18](https://github.com/immi420/crystal_navigation_bar/assets/50419120/eefd8199-b587-4bf2-b10b-3e8552fa2254)
![Simulator Screenshot - iPhone 15 Pro - 2024-01-07 at 05 24 25](https://github.com/immi420/crystal_navigation_bar/assets/50419120/7747c469-ad81-44c8-aff3-7006ded547ca)

**Comment by immi420** [comment]
Can you provide reproducable code?
What i understand you are trying to change screens using navigator?
You don't need to use navigator to change screens only index needs to be updated.
You can check example or provide your code or explain your specific scenario.
