### ISSUE TITLE
BorderWidth

### ISSUE THREAD

**Issue by ghost** [immi420/crystal_navigation_bar#4]
I was wondering how you could modify the border width of the navbar, because I have no idea.

**Comment by immi420** [comment]
Hey, 
Thank You for using this package 📦.
Only borderColor can be changed. Border width is fixed.
If you still need to change the border width I'll add support for it and release a new version.

**Comment by LawrenZzz** [comment]
This feature is highly needed! I really love the effect of the crystal navigation bar you created, but it looks a bit small on my phone. Could you please add support for boundary width, which would be very helpful to me.

**Comment by immi420** [comment]
Border width Added in new release.
